version: '3'

services:

  gestion:
    container_name: gestion_gonzalonazareno_org
    image: josedom24/gestion:$VERSION_DEPLOY
    volumes:
      - /opt/gestion/basededatos:/usr/share/app/basededatos
    ports:
      - '$PORT_DEPLOY:8000'
    
    restart: always
