version: '3'

services:

  gestion:
    container_name: gestion_gonzalonazareno_org
    image: iesgn/gestion:$VERSION_DEPLOY
    volumes:
      - /opt/gestion/basededatos:/gestion/basededatos
    ports:
      - '$PORT_DEPLOY:8000'
    
    restart: always